//given share prices for a particular period in the form of array elements.write a method to find the max profit that can be generated by buying and selling shares only once.at the end also display the buy price and sale price along with the max profit.


public class maxprofit {
    static int buyPrice = 0;
    static int sellPrice = 0;
    public static int findMaxProfit(int[] prices) {
        if (prices == null || prices.length < 2) {
            return 0; // Not enough data to make a profit
        }
        

        int minPrice = prices[0];
        int maxProfit = 0;
        buyPrice = prices[0];
        sellPrice = prices[0];

        for(int i=0;i<prices.length;i++){
            if (prices[i]<minPrice){
                minPrice=prices[i];
            }
            else if(prices[i]-minPrice>maxProfit){
                maxProfit=prices[i]-minPrice;
                buyPrice=minPrice;
                sellPrice=prices[i];
            }
        }
        return maxProfit;

    }
    public static void main(String[] args) {
        int[] prices = {7, 1, 5, 3, 6, 4};
        int maxProfit = findMaxProfit(prices);
        System.out.println("Maximum Profit: " + maxProfit);
        System.out.println("Buy Price: " + buyPrice);
        System.out.println("Sell Price: " + sellPrice);
    }
}
